/*
	[03/30/2023]
	ZERO COOLS WELCOME.SQF SCRIPT
		TO RUN ADD THIS TO INITPLAYERLOCAL.SQF
			[] execVM "ADDONS\WELCOME.sqf";
			
			
	PLAYS SONG AND SHOWS IMAGE FOR PLAYERS THAT JUST JOINNED
	EXAMPLE PHOTO SHOWN IN PICTURES FOLDER
	ONLY .PAA PHOTOS WORK
	2X1 RATIO OR 1X1 WILL WORK
	
	IF CREATING YOUR OWN IMAGE
	IMAGE WILL SHRINK HORIZONTALLY SO YOULL NEED TO OVER STRETCH YOUR OWN TO COMPENSATE
	
	
	
*/

	waitUntil {!isNull findDisplay 46 && !isNil 'ExileClientLoadedIn' && getPlayerUID player != ''};  
	if ( alive player ) then 
		{	
			uiSleep 1;
			/*
				ONLY USE ONE SOUND PLAY METHOD
				PUT "//" ON THE SOUND COMMAND YOU DO NOT WANT USED.
				PUT "//" ON BOTH PLAYSOUND AND SAY3D IF YOU DONT WANT EITHER TO BE USED
				CHANGE "ANTHEM" TO YOUR PREFERED SONG/SOUND 
			*/
			
			// PLAY SONG FOR PLAYER ONLY, NO OTHERS CAN HEAR IT
			playSound "ANTHEM";
			
			// PLAY SONG FROM PLAYER POSITION INSTEAD, SO OTHERS CAN HEAR IT
			//say3d "ANTHEM";
			
			// PUZZLE PEICE APPEAR THEN FADE AWAY
			//["DIRECTORY\PICTURE.paa",[x, y, width, hieght],[width, hieght],duration,fadeInOutTime,tileTransparency] spawn BIS_fnc_textTiles
			["PICTURES\OFGWELCOME.paa",[0,0,1,1],[5,5],5,2,0.3] spawn BIS_fnc_textTiles;	
		};


